# Configuration du serveur
server.port=8085

# Configuration de la base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/digitalbank?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (désactivée par défaut - décommentez pour les tests)
#spring.datasource.url=jdbc:h2:mem:digitalbank
#spring.h2.console.enabled=true
